import {type Stack, STACK_TYPE, type StackAutocomplete} from "~/types";

export const MOCKS_AUTO_COMPLETE = [
    { value: 'react', label: 'React' },
    { value: 'vue', label: 'Vue' },
    { value: 'nuxt', label: 'Nuxt' },
    { value: 'angular', label: 'Angular' },
    { value: 'svelte', label: 'Svelte' },
    { value: 'ember', label: 'Ember' },
    { value: 'backbone', label: 'Backbone' },
    { value: 'jquery', label: 'jQuery' },
    { value: 'bootstrap', label: 'Bootstrap' },
    { value: 'tailwind', label: 'Tailwind' },
    { value: 'bulma', label: 'Bulma' },
    { value: 'materialize', label: 'Materialize' },
    { value: 'foundation', label: 'Foundation' },
    { value: 'semantic', label: 'Semantic' },
    { value: 'ant', label: 'Ant' },
    { value: 'chakra', label: 'Chakra' },
    { value: 'vuetify', label: 'Vuetify' },
    { value: 'quasar', label: 'Quasar' },
    { value: 'buefy', label: 'Buefy' },
    { value: 'express', label: 'Express' },
    { value: 'nestjs', label: 'NestJS' },
    { value: 'django', label: 'Django' },
    { value: 'flask', label: 'Flask' },
    { value: 'spring', label: 'Spring' },
    { value: 'rails', label: 'Rails' },
    { value: 'laravel', label: 'Laravel' },
    { value: 'aspnet', label: 'ASP.NET' },
    { value: 'docker', label: 'Docker' },
    { value: 'kubernetes', label: 'Kubernetes' },
    { value: 'terraform', label: 'Terraform' },
    { value: 'ansible', label: 'Ansible' },
    { value: 'jenkins', label: 'Jenkins' },
    { value: 'travis', label: 'Travis' },
    { value: 'circleci', label: 'CircleCI' },
    { value: 'github_actions', label: 'GitHub Actions' },
    { value: 'aws', label: 'AWS' },
    { value: 'gcp', label: 'GCP' },
    { value: 'azure', label: 'Azure' }
];

export const MOCKS_STACKS: Stack[] = [
    {
        "name": "React",
        "documentation_link": "https://reactjs.org/docs/getting-started.html",
        "stack_type": STACK_TYPE.FRAMEWORK,
        "last_version": "17.0.2",
        "description": "A JavaScript library for building user interfaces.",
        "languages": "JavaScript",
        "frontend_stack": true,
        "backend_stack": false,
        "logo_url": "https://reactjs.org/logo-og.png"
    },
    {
        "name": "Vue.js",
        "documentation_link": "https://v3.vuejs.org/guide/introduction.html",
        "stack_type": STACK_TYPE.FRAMEWORK,
        "last_version": "3.0.0",
        "description": "A progressive JavaScript framework for building modern web applications.",
        "languages": "JavaScript",
        "frontend_stack": true,
        "backend_stack": false,
        "logo_url": "https://vuejs.org/images/logo.png"
    },
    {
        "name": "Nuxt.js",
        "documentation_link": "https://nuxtjs.org/docs/2.x/get-started/installation",
        "stack_type": STACK_TYPE.FRAMEWORK,
        "last_version": "2.15.3",
        "description": "A framework for creating Universal Vue.js Applications.",
        "languages": "JavaScript",
        "frontend_stack": true,
        "backend_stack": false,
        "logo_url": "https://nuxtjs.org/logos/nuxt-icon.png"
    },
    {
        "name": "Angular",
        "documentation_link": "https://angular.io/docs",
        "stack_type": STACK_TYPE.FRAMEWORK,
        "last_version": "12.0.0",
        "description": "A platform for building mobile and desktop web applications.",
        "languages": "TypeScript",
        "frontend_stack": true,
        "backend_stack": false,
        "logo_url": "https://angular.io/assets/images/logos/angular/angular.png"
    },
    {
        "name": "Svelte",
        "documentation_link": "https://svelte.dev/docs",
        "stack_type": STACK_TYPE.FRAMEWORK,
        "last_version": "3.38.2",
        "description": "A radical new approach to building user interfaces.",
        "languages": "JavaScript",
        "frontend_stack": true,
        "backend_stack": false,
        "logo_url": "https://svelte.dev/svelte-logo-horizontal.svg"
    },
    {
        "name": "Ember.js",
        "documentation_link": "https://emberjs.com/",
        "stack_type": STACK_TYPE.FRAMEWORK,
        "last_version": "3.28.0",
        "description": "A framework for ambitious web developers.",
        "languages": "JavaScript",
        "frontend_stack": true,
        "backend_stack": false,
        "logo_url": "https://emberjs.com/images/brand/ember-ember.png"
    },
    {
        "name": "Backbone.js",
        "documentation_link": "https://backbonejs.org/",
        "stack_type": STACK_TYPE.FRAMEWORK,
        "last_version": "1.4.0",
        "description": "Give your JS app some backbone with Models, Views, Collections, and Events.",
        "languages": "JavaScript",
        "frontend_stack": true,
        "backend_stack": false,
        "logo_url": "https://backbonejs.org/docs/images/backbone.png"
    },
    {
        "name": "jQuery",
        "documentation_link": "https://jquery.com/",
        "stack_type": STACK_TYPE.LIBRAIRIE,
        "last_version": "3.6.0",
        "description": "A fast, small, and feature-rich JavaScript library.",
        "languages": null,
        "frontend_stack": true,
        "backend_stack": false,
        "logo_url": "https://jquery.com/jquery-wp-content/themes/jquery/content/donate/jquery-logo.png"
    },
    {
        "name": "Bootstrap",
        "documentation_link": "https://getbootstrap.com/docs/5.0/getting-started/introduction/",
        "stack_type": STACK_TYPE.LIBRAIRIE,
        "last_version": "5.0.0",
        "description": "The most popular HTML, CSS, and JS library in the world.",
        "languages": null,
        "frontend_stack": true,
        "backend_stack": false,
        "logo_url": "https://getbootstrap.com/docs/5.0/assets/brand/bootstrap-logo-shadow.png"
    },
    {
        "name": "Tailwind CSS",
        "documentation_link": "https://tailwindcss.com/docs",
        "stack_type": STACK_TYPE.LIBRAIRIE,
        "last_version": "2.2.4",
        "description": "A utility-first CSS framework for rapidly building custom designs.",
        "languages": null,
        "frontend_stack": true,
        "backend_stack": false,
        "logo_url": "https://tailwindcss.com/_next/static/media/social-card-large.a2b90b5c0fb95f34fbf6d603b74e499b.jpg"
    },
    {
        "name": "Bulma",
        "documentation_link": "https://bulma.io/documentation/",
        "stack_type": STACK_TYPE.LIBRAIRIE,
        "last_version": "0.9.3",
        "description": "A modern CSS framework based on Flexbox.",
        "languages": null,
        "frontend_stack": true,
        "backend_stack": false,
        "logo_url": "https://bulma.io/images/bulma-logo.png"
    },
    {
        "name": "Materialize",
        "documentation_link": "https://materializecss.com/getting-started.html",
        "stack_type": STACK_TYPE.LIBRAIRIE,
        "last_version": "1.0.0",
        "description": "A modern responsive front-end framework based on Material Design.",
        "languages": null,
        "frontend_stack": true,
        "backend_stack": false,
        "logo_url": "https://materializecss.com/images/logo.png"
    },
    {
        "name": "Foundation",
        "documentation_link": "https://get.foundation/sites/docs/",
        "stack_type": STACK_TYPE.LIBRAIRIE,
        "last_version": "6.6.3",
        "description": "The most advanced responsive front-end framework in the world.",
        "languages": null,
        "frontend_stack": true,
        "backend_stack": false,
        "logo_url": "https://foundation.zurb.com/assets/img/brand-foundation3.png"
    },
    {
        "name": "Semantic UI",
        "documentation_link": "https://semantic-ui.com/",
        "stack_type": STACK_TYPE.LIBRAIRIE,
        "last_version": "2.4.2",
        "description": "A development framework that helps create beautiful, responsive layouts using human-friendly HTML.",
        "languages": null,
        "frontend_stack": true,
        "backend_stack": false,
        "logo_url": "https://semantic-ui.com/images/logo.png"
    },
    {
        "name": "Ant Design",
        "documentation_link": "https://ant.design/docs/react/introduce",
        "stack_type": STACK_TYPE.LIBRAIRIE,
        "last_version": "4.16.13",
        "description": "A design system for enterprise-level products. Create an efficient and enjoyable work experience.",
        "languages": null,
        "frontend_stack": true,
        "backend_stack": false,
        "logo_url": "https://gw.alipayobjects.com/zos/rmsportal/XzONkEqftXthpqG.png"
    },
    {
        "name": "Chakra UI",
        "documentation_link": "https://chakra-ui.com/docs/getting-started",
        "stack_type": STACK_TYPE.LIBRAIRIE,
        "last_version": "1.6.5",
        "description": "A simple, modular and accessible component library that gives you the building blocks you need to build your React applications.",
        "languages": null,
        "frontend_stack": true,
        "backend_stack": false,
        "logo_url": "https://chakra-ui.com/logo.svg"
    },
    {
        "name": "Vuetify",
        "documentation_link": "https://vuetifyjs.com/en/getting-started/installation/",
        "stack_type": STACK_TYPE.LIBRAIRIE,
        "last_version": "2.5.0",
        "description": "A Vue UI Library with beautifully handcrafted Material Components.",
        "languages": null,
        "frontend_stack": true,
        "backend_stack": false,
        "logo_url": "https://cdn.vuetifyjs.com/images/logos/vuetify-logo-dark.png"
    },
    {
        "name": "Quasar",
        "documentation_link": "https://quasar.dev/start",
        "stack_type": STACK_TYPE.FRAMEWORK,
        "last_version": "1.15.10",
        "description": "A framework for building high-performance VueJS user interfaces.",
        "languages": "JavaScript",
        "frontend_stack": true,
        "backend_stack": false,
        "logo_url": "https://cdn.quasar.dev/logo-v2/svg/quasar-logo.svg"
    },
    {
        "name": "Buefy",
        "documentation_link": "https://buefy.org/documentation",
        "stack_type": STACK_TYPE.LIBRAIRIE,
        "last_version": "0.9.10",
        "description": "Lightweight UI components for Vue.js based on Bulma.",
        "languages": null,
        "frontend_stack": true,
        "backend_stack": false,
        "logo_url": "https://buefy.org/static/img/buefy.1d65c18.svg"
    },
    {
        "name": "Express",
        "documentation_link": "https://expressjs.com/en/starter/installing.html",
        "stack_type": STACK_TYPE.FRAMEWORK,
        "last_version": "4.17.1",
        "description": "A minimal and flexible Node.js web application framework.",
        "languages": "JavaScript",
        "frontend_stack": false,
        "backend_stack": true,
        "logo_url": "https://expressjs.com/images/express-facebook-share.png"
    },
    {
        "name": "NestJS",
        "documentation_link": "https://docs.nestjs.com/",
        "stack_type": STACK_TYPE.FRAMEWORK,
        "last_version": "7.6.15",
        "description": "A progressive Node.js framework for building efficient, reliable and scalable server-side applications.",
        "languages": "JavaScript",
        "frontend_stack": false,
        "backend_stack": true,
        "logo_url": "https://docs.nestjs.com/assets/logo-small.svg"
    },
    {
        "name": "Django",
        "documentation_link": "https://docs.djangoproject.com/en/stable/",
        "stack_type": STACK_TYPE.FRAMEWORK,
        "last_version": "3.2.5",
        "description": "A high-level Python Web framework that encourages rapid development and clean, pragmatic design.",
        "languages": "Python",
        "frontend_stack": false,
        "backend_stack": true,
        "logo_url": "https://static.djangoproject.com/img/logos/django-logo-negative.png"
    },
    {
        "name": "Flask",
        "documentation_link": "https://flask.palletsprojects.com/en/2.0.x/",
        "stack_type": STACK_TYPE.FRAMEWORK,
        "last_version": "2.0.1",
        "description": "A lightweight WSGI web application framework in Python.",
        "languages": "Python",
        "frontend_stack": false,
        "backend_stack": true,
        "logo_url": "https://flask.palletsprojects.com/en/2.0.x/_static/flask-icon.png"
    },
    {
        "name": "Spring",
        "documentation_link": "https://spring.io/projects/spring-framework",
        "stack_type": STACK_TYPE.FRAMEWORK,
        "last_version": "5.3.9",
        "description": "Provides a comprehensive programming and configuration model for modern Java-based enterprise applications.",
        "languages": "Java",
        "frontend_stack": false,
        "backend_stack": true,
        "logo_url": "https://spring.io/images/icon-spring-b6e9ccabe9dc89c7e031bf411f310326.svg"
    },
    {
        "name": "Rails",
        "documentation_link": "https://guides.rubyonrails.org/",
        "stack_type": STACK_TYPE.FRAMEWORK,
        "last_version": "6.1.4",
        "description": "A web-application framework that includes everything needed to create database-backed web applications according to the Model-View-Controller (MVC) pattern.",
        "languages": "Ruby",
        "frontend_stack": false,
        "backend_stack": true,
        "logo_url": "https://rubyonrails.org/images/rails-logo.svg"
    },
    {
        "name": "Laravel",
        "documentation_link": "https://laravel.com/docs/8.x",
        "stack_type": STACK_TYPE.FRAMEWORK,
        "last_version": "8.5.0",
        "description": "A PHP framework for web artisans.",
        "languages": "PHP",
        "frontend_stack": false,
        "backend_stack": true,
        "logo_url": "https://laravel.com/img/logomark.min.svg"
    },
    {
        "name": "ASP.NET",
        "documentation_link": "https://docs.microsoft.com/en-us/aspnet/core/?view=aspnetcore-5.0",
        "stack_type": STACK_TYPE.FRAMEWORK,
        "last_version": "5.0.7",
        "description": "A free, cross-platform, open-source framework for building modern, cloud-based, internet-connected applications.",
        "languages": "C#",
        "frontend_stack": false,
        "backend_stack": true,
        "logo_url": "https://docs.microsoft.com/en-us/media/logos/logo-ms-social.png"
    },
    {
        "name": "Docker",
        "documentation_link": "https://docs.docker.com/get-started/",
        "stack_type": STACK_TYPE.LIBRAIRIE,
        "last_version": "20.10.7",
        "description": "An open platform for developing, shipping, and running applications.",
        "languages": null,
        "frontend_stack": false,
        "backend_stack": true,
        "logo_url": "https://www.docker.com/sites/default/files/d8/2019-07/vertical-logo-monochromatic.png"
    },
    {
        "name": "Kubernetes",
        "documentation_link": "https://kubernetes.io/docs/home/",
        "stack_type": STACK_TYPE.LIBRAIRIE,
        "last_version": "1.21.3",
        "description": "An open-source system for automating deployment, scaling, and management of containerized applications.",
        "languages": null,
        "frontend_stack": false,
        "backend_stack": true,
        "logo_url": "https://kubernetes.io/images/kubernetes-horizontal-color.png"
    },
    {
        "name": "Terraform",
        "documentation_link": "https://www.terraform.io/docs",
        "stack_type": STACK_TYPE.LIBRAIRIE,
        "last_version": "1.0.3",
        "description": "An open-source infrastructure as code software tool that enables you to safely and predictably create, change, and improve infrastructure.",
        "languages": null,
        "frontend_stack": false,
        "backend_stack": true,
        "logo_url": "https://www.terraform.io/assets/images/og-image-8b3e4f7d.png"
    },
    {
        "name": "Ansible",
        "documentation_link": "https://docs.ansible.com/ansible/latest/index.html",
        "stack_type": STACK_TYPE.LIBRAIRIE,
        "last_version": "2.11.2",
        "description": "An open-source software provisioning, configuration management, and application-deployment tool enabling infrastructure as code.",
        "languages": null,
        "frontend_stack": false,
        "backend_stack": true,
        "logo_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Ansible_logo.svg/2560px-Ansible_logo.svg.png"
    },
    {
        "name": "Jenkins",
        "documentation_link": "https://www.jenkins.io/doc/",
        "stack_type": STACK_TYPE.LIBRAIRIE,
        "last_version": "2.289.1",
        "description": "An open-source automation server which enables developers around the world to reliably build, test, and deploy their software.",
        "languages": null,
        "frontend_stack": false,
        "backend_stack": true,
        "logo_url": "https://www.jenkins.io/images/logos/jenkins/jenkins.svg"
    },
    {
        "name": "Travis CI",
        "documentation_link": "https://docs.travis-ci.com/",
        "stack_type": STACK_TYPE.LIBRAIRIE,
        "last_version": "1.0.0",
        "description": "A hosted continuous integration service used to build and test software projects hosted on GitHub and Bitbucket.",
        "languages": null,
        "frontend_stack": false,
        "backend_stack": true,
        "logo_url": "https://travis-ci.com/images/logos/TravisCI-Mascot-1.png"
    },
    {
        "name": "CircleCI",
        "documentation_link": "https://circleci.com/docs/",
        "stack_type": STACK_TYPE.LIBRAIRIE,
        "last_version": "1.0.0",
        "description": "A continuous integration and delivery platform that helps software teams work smarter, faster.",
        "languages": null,
        "frontend_stack": false,
        "backend_stack": true,
        "logo_url": "https://circleci.com/docs/assets/img/logos/circleci-logo-stacked-fb3e2d4894b1f869a6aade1e94042d7f.svg"
    },
    {
        "name": "GitHub Actions",
        "documentation_link": "https://docs.github.com/en/actions",
        "stack_type": STACK_TYPE.LIBRAIRIE,
        "last_version": "1.0.0",
        "description": "An API for orchestrating any workflow, based on any event.",
        "languages": null,
        "frontend_stack": false,
        "backend_stack": true,
        "logo_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
    },
    {
        "name": "AWS",
        "documentation_link": "https://aws.amazon.com/documentation/",
        "stack_type": STACK_TYPE.LIBRAIRIE,
        "last_version": "latest",
        "description": "Amazon Web Services offers reliable, scalable, and inexpensive cloud computing services.",
        "languages": null,
        "frontend_stack": false,
        "backend_stack": true,
        "logo_url": "https://a0.awsstatic.com/libra-css/images/logos/aws_logo_smile_1200x630.png"
    },
    {
        "name": "Google Cloud Platform",
        "documentation_link": "https://cloud.google.com/docs",
        "stack_type": STACK_TYPE.LIBRAIRIE,
        "last_version": "latest",
        "description": "A suite of cloud computing services that runs on the same infrastructure that Google uses internally for its end-user products.",
        "languages": null,
        "frontend_stack": false,
        "backend_stack": true,
        "logo_url": "https://cloud.google.com/images/social-icon-google-cloud-1200-630.png"
    },
    {
        "name": "Azure",
        "documentation_link": "https://docs.microsoft.com/en-us/azure/",
        "stack_type": STACK_TYPE.LIBRAIRIE,
        "last_version": "latest",
        "description": "Microsoft Azure is an ever-expanding set of cloud services to help your organization meet your business challenges.",
        "languages": null,
        "frontend_stack": false,
        "backend_stack": true,
        "logo_url": "https://azurecomcdn.azureedge.net/cvt-466fb5d098184ef2bb71fc450d7a0bb1072de2a5b5fd8af3280b1bba20f1cfc1/images/icon/icon-72-white.png"
    }
]